// <auto-generated />
using APILocalBiz.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APILocalBiz.Migrations
{
    [DbContext(typeof(APILocalBizContext))]
    partial class APILocalBizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APILocalBiz.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cuisine");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<bool>("Recommended");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Cuisine = "Steak",
                            Name = "El Gaucho",
                            Phone = "206-728-1337",
                            Recommended = true
                        },
                        new
                        {
                            RestaurantId = 2,
                            Cuisine = "Greek",
                            Name = "Kafe Neo",
                            Phone = "425-375-0512",
                            Recommended = true
                        },
                        new
                        {
                            RestaurantId = 3,
                            Cuisine = "Japanese",
                            Name = "Sushi Spott",
                            Phone = "425-338-4553",
                            Recommended = false
                        });
                });

            modelBuilder.Entity("APILocalBiz.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<bool>("Recommended");

                    b.Property<string>("Specialty");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Name = "Francesca's",
                            Phone = "425-775-4712",
                            Recommended = true,
                            Specialty = "Women's Fashion"
                        },
                        new
                        {
                            ShopId = 2,
                            Name = "Central Market",
                            Phone = "425-357-3240",
                            Recommended = true,
                            Specialty = "Gourmet Grocery"
                        },
                        new
                        {
                            ShopId = 3,
                            Name = "Mill Geek Comics",
                            Phone = "425-415-6666",
                            Recommended = true,
                            Specialty = "Comic books"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
